/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetfood.gui;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import planetfood.pojo.UserProfile;

/**
 *
 * @author Dell
 */
public class AdminOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    public AdminOptionsFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
        jlName.setText("Hello "+UserProfile.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jrbAddEmployee = new javax.swing.JRadioButton();
        jrbViewEmployee = new javax.swing.JRadioButton();
        jrbRemoveEmployee = new javax.swing.JRadioButton();
        jrbEditEmployee = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jrbRegisterCashier = new javax.swing.JRadioButton();
        jrbRemoveCashier = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jrbViewOrders = new javax.swing.JRadioButton();
        jrbViewDateWise = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jrbAddCategory = new javax.swing.JRadioButton();
        jrbEditCategory = new javax.swing.JRadioButton();
        jrbViewCategory = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jrbAddProduct = new javax.swing.JRadioButton();
        jrbViewProduct = new javax.swing.JRadioButton();
        jrbEditProduct = new javax.swing.JRadioButton();
        jrbRemoveProduct = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jlName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLANET FOOD ADMIN PANEL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Make A Choice");

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emp Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbAddEmployee.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbAddEmployee);
        jrbAddEmployee.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddEmployee.setText("Add Emp");
        jrbAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAddEmployeeActionPerformed(evt);
            }
        });

        jrbViewEmployee.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbViewEmployee);
        jrbViewEmployee.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbViewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewEmployee.setText("View Emp");
        jrbViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbViewEmployeeActionPerformed(evt);
            }
        });

        jrbRemoveEmployee.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbRemoveEmployee);
        jrbRemoveEmployee.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbRemoveEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jrbRemoveEmployee.setText("Remove Emp");

        jrbEditEmployee.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbEditEmployee);
        jrbEditEmployee.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbEditEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditEmployee.setText("Edit Emp");
        jrbEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEditEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbViewEmployee)
                    .addComponent(jrbEditEmployee)
                    .addComponent(jrbRemoveEmployee)
                    .addComponent(jrbAddEmployee))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbAddEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbViewEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbEditEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbRemoveEmployee)
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cashier Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbRegisterCashier.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbRegisterCashier);
        jrbRegisterCashier.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbRegisterCashier.setForeground(new java.awt.Color(255, 255, 255));
        jrbRegisterCashier.setText("Register Cashier");

        jrbRemoveCashier.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbRemoveCashier);
        jrbRemoveCashier.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbRemoveCashier.setForeground(new java.awt.Color(255, 255, 255));
        jrbRemoveCashier.setText("Remove Cashier");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRemoveCashier)
                    .addComponent(jrbRegisterCashier))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbRegisterCashier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbRemoveCashier)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbViewOrders.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbViewOrders);
        jrbViewOrders.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewOrders.setText("View Orders");
        jrbViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbViewOrdersActionPerformed(evt);
            }
        });

        jrbViewDateWise.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbViewDateWise);
        jrbViewDateWise.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbViewDateWise.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewDateWise.setText("View DateWise");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbViewOrders)
                    .addComponent(jrbViewDateWise))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbViewOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbViewDateWise)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbAddCategory.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbAddCategory);
        jrbAddCategory.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbAddCategory.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddCategory.setText("Add Category");

        jrbEditCategory.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbEditCategory);
        jrbEditCategory.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbEditCategory.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditCategory.setText("Edit Category");

        jrbViewCategory.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbViewCategory);
        jrbViewCategory.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbViewCategory.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewCategory.setText("View Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbAddCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jrbEditCategory, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jrbViewCategory)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbAddCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbEditCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbViewCategory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jrbAddProduct.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbAddProduct);
        jrbAddProduct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddProduct.setText("Add Product");

        jrbViewProduct.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbViewProduct);
        jrbViewProduct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbViewProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbViewProduct.setText("View Product");

        jrbEditProduct.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbEditProduct);
        jrbEditProduct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbEditProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbEditProduct.setText("Edit Product");

        jrbRemoveProduct.setBackground(new java.awt.Color(0, 153, 102));
        buttonGroup1.add(jrbRemoveProduct);
        jrbRemoveProduct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jrbRemoveProduct.setForeground(new java.awt.Color(255, 255, 255));
        jrbRemoveProduct.setText("Remove Product");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRemoveProduct)
                    .addComponent(jrbAddProduct)
                    .addComponent(jrbViewProduct)
                    .addComponent(jrbEditProduct))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbAddProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbEditProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbViewProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbRemoveProduct)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DoTask");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlName.setForeground(new java.awt.Color(255, 255, 255));
        jlName.setText("jLabel3");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\ff.jpg")); // NOI18N

        jlLogout.setForeground(new java.awt.Color(255, 255, 255));
        jlLogout.setText("Logout");
        jlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlLogout))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogout)
                            .addComponent(jLabel3))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlName)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAddEmployeeActionPerformed

    private void jrbViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbViewEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbViewEmployeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
      /*  if(jrbAddEmployee.isSelected())
        {
            AddEmpFrame ae=new AddEmpFrame();
            ae.setVisible(true);
            this.dispose();
        }*/
      String task=getOption();
      if(task==null)
      {
          JOptionPane.showMessageDialog(null, "PLEASE CHOOSE THE OPTION", "ERROR!!", JOptionPane.ERROR_MESSAGE);
          return;
      }
      JFrame jf=null;
      if(task.equals("Add Emp"))
      {
        jf=new AddEmpFrame();
        
      }
      else if(task.equals("View Emp"))
      {
        jf=new ViewEmpFrame();
        
      }
      else if(task.equals("Edit Emp"))
      {
        jf=new EditEmpFrame();
        
      }
      else if(task.equals("Remove Emp"))
      {
        jf=new RemoveEmpFrame();
        
      }
      else if(task.equals("Add Product"))
      {
        jf=new AddProductFrame();
        
      }
      else if(task.equals("Remove Product"))
      {
        jf=new RemoveProductFrame();
        
      }
      else if(task.equals("View Product"))
      {
        jf=new ViewProductsFrame();
        
      }
      else if(task.equals("Edit Product"))
      {
        jf=new EditProductFrame();
        
      }
       else if(task.equals("Remove Cashier"))
      {
        jf=new RemoveCashierFrame();
        
      }
      else if(task.equals("Register Cashier"))
      {
        jf=new RegisterCashierFrame();
        
      }
       else if(task.equals("Add Category"))
      {
        jf=new AddCategoryFrame();
        
      }
     
      else if(task.equals("View Category"))
      {
        jf=new ViewAllCategoriesFrame();
        
      }
      else if(task.equals("Edit Category"))
      {
        jf=new EditCategoryFrame();
        
      }
       else if(task.equals("View Orders"))
      {
        jf=new ViewAllOrdersFrame();
        
      }
      else if(task.equals("View DateWise"))
      {
        jf=new ViewAllDateOrdersFrame();
        
      }
      this.dispose();
      jf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLogoutMouseEntered
        jlLogout.setForeground(Color.yellow);
    }//GEN-LAST:event_jlLogoutMouseEntered

    private void jlLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLogoutMouseExited
        // TODO add your handling code here:
         jlLogout.setForeground(Color.white);
    }//GEN-LAST:event_jlLogoutMouseExited

    private void jlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginFrame l=new LoginFrame();
        l.setVisible(true);
    }//GEN-LAST:event_jlLogoutMouseClicked

    private void jrbEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEditEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEditEmployeeActionPerformed

    private void jrbViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbViewOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbViewOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionsFrame().setVisible(true);
            }
        });
    }

    public String getOption()
    {
        if(jrbAddEmployee.isSelected())
        {
         return jrbAddEmployee.getText();
        }
        else if(jrbEditEmployee.isSelected())
             return jrbEditEmployee.getText();
         else if(jrbViewEmployee.isSelected())
             return jrbViewEmployee.getText();
         else if(jrbRemoveEmployee.isSelected())
             return jrbRemoveEmployee.getText();
         else if(jrbAddProduct.isSelected())
             return jrbAddProduct.getText();
         else if(jrbEditProduct.isSelected())
             return jrbEditProduct.getText();
         else if(jrbViewProduct.isSelected())
             return jrbViewProduct.getText();
         else if(jrbRemoveProduct.isSelected())
             return jrbRemoveProduct.getText();
         /*else if(jrbEditEmployee.isSelected())
             return jrbEditEmployee.getText();
         else if(jrbEditEmployee.isSelected())
             return jrbEditEmployee.getText();*/
          else if(jrbRegisterCashier.isSelected())
             return jrbRegisterCashier.getText();
         else if(jrbRemoveCashier.isSelected())
             return jrbRemoveCashier.getText();
         // ..........................................
          else if(jrbAddCategory.isSelected())
             return jrbAddCategory.getText();
         else if(jrbEditCategory.isSelected())
             return jrbEditCategory.getText();
         else if(jrbViewCategory.isSelected())
             return jrbViewCategory.getText();
         //..............................................
           else if(jrbViewOrders.isSelected())
             return jrbViewOrders.getText();
         else if(jrbViewDateWise.isSelected())
             return jrbViewDateWise.getText();
         else 
             return null;
         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlLogout;
    private javax.swing.JLabel jlName;
    private javax.swing.JRadioButton jrbAddCategory;
    private javax.swing.JRadioButton jrbAddEmployee;
    private javax.swing.JRadioButton jrbAddProduct;
    private javax.swing.JRadioButton jrbEditCategory;
    private javax.swing.JRadioButton jrbEditEmployee;
    private javax.swing.JRadioButton jrbEditProduct;
    private javax.swing.JRadioButton jrbRegisterCashier;
    private javax.swing.JRadioButton jrbRemoveCashier;
    private javax.swing.JRadioButton jrbRemoveEmployee;
    private javax.swing.JRadioButton jrbRemoveProduct;
    private javax.swing.JRadioButton jrbViewCategory;
    private javax.swing.JRadioButton jrbViewDateWise;
    private javax.swing.JRadioButton jrbViewEmployee;
    private javax.swing.JRadioButton jrbViewOrders;
    private javax.swing.JRadioButton jrbViewProduct;
    // End of variables declaration//GEN-END:variables
}
